os:
  - linux
  - osx
language: generic
sudo: required
dist: trusty
# osx_image: xcode7.2
install:
  - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
  - swiftenv install 4.0
script:
  - swift test

